import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;


public class AreaCodigo extends javax.swing.JPanel {
    
    private int counter;
    private ArrayList<JLabel> nl;
    private Font formato;
        
    public AreaCodigo() {
        jTextArea = new javax.swing.JTextArea();
        jPanenum = new javax.swing.JPanel();
        
        initComponents();      
        
        jTextArea.addCaretListener(new CaretListener(){
            public void caretUpdate(CaretEvent e ) {
                actNoLinea(e);
                }
            }
        );
        //----------------------------------------------------------------------
        jPanenum.setPreferredSize(new Dimension(40, 100));
        jPanenum.setLayout(null);
        /*jPanenum.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                public void mouseMoved(java.awt.event.MouseEvent evt){
                    System.out.println(evt.getX()+", "+evt.getY()+"\n");
                }
        });*/
        

        setLayout(new java.awt.BorderLayout());

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
               
        add(jTextArea, java.awt.BorderLayout.CENTER);
        //jPanel1.add(jPanenum, java.awt.BorderLayout.LINE_START);
        add(jPanenum, java.awt.BorderLayout.WEST);
        //----------------------------------------------------------------------
        
        nl = new ArrayList<>();
        counter = 1;
        formato = new Font("Monospaced", Font.PLAIN, 14);
                
        nl.add(new JLabel("1"));
        nl.get(0).setFont(formato);
        
        jPanenum.add(nl.get(0)); 
        jPanenum.setVisible(true);
        
        nl.get(0).setBounds(0, 5, 34, 18);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );        
    }// </editor-fold>//GEN-END:initComponents
    private void actNoLinea(CaretEvent e){
       int opc = jTextArea.getLineCount();
       if(opc  == counter){
           return;
       }
       if(opc > counter){
        agregarLinea();
        }
       if(opc < counter){
        quitarLinea();
        }
   }
   
   
    public void agregarLinea(){
        int e = 4+16*counter;
        counter++;
        nl.add(new JLabel(counter+""));
        nl.get(counter-1).setFont(formato);
        nl.get(counter-1).setVerticalAlignment(JLabel.TOP);
        
        jPanenum.add(nl.get(counter-1));
        //showMessageDialog(this,e+"");
        nl.get(counter-1).setBounds(0,e,34,15);
        jPanenum.updateUI();
    }
    
    public void quitarLinea(){
        if(counter > 1){
            counter--;
            jPanenum.remove(nl.get(counter));
            nl.remove(counter);
            jPanenum.updateUI();
            updateUI();
        }
        
    }    
    
    private javax.swing.JPanel jPanenum;
    public javax.swing.JTextArea jTextArea;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}