
import java.awt.Color;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Hashtable;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.JLabel;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abv17
 */
public class Interfaz extends javax.swing.JFrame {
    Hashtable<String, Simbolo> tablaSimbolos;
    String[] palRes={"start","end","natural","integer","real","function","table","text","bit","infinity","main",
                     "pi","euler","if","else","during","from","to","do","terminal","expression","thread","convertion"};
    int fila;
    int col;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        tablaSimbolos = new Hashtable<>();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        areaCodigo.setPreferredSize(new Dimension(this.getSize().width, this.getSize().height/2));
        areaCodigo.addCaretListener(new CaretListener(){
            @Override
            public void caretUpdate(CaretEvent ce) {
                JTextArea codigo = (JTextArea)ce.getSource();
                try{
                    int pos =codigo.getCaretPosition();
                    fila=codigo.getLineOfOffset(pos);
                    col = pos-codigo.getLineStartOffset(fila)+1;
                    fila++;
                }catch(Exception e){}
                update(fila, col);
            }
        });
        panelPrincipal.setBackground(Color.LIGHT_GRAY);
        areaCodigo.requestFocus();
    }
    private void update(int fil, int co){
        numFilas.setText(fil+"");
        numCol.setText(co+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        panelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaCodigo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaComponentesL = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        numFilas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numCol = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        areaCodigo.setColumns(20);
        areaCodigo.setRows(5);
        areaCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                areaCodigoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(areaCodigo);

        AreaComponentesL.setEditable(false);
        AreaComponentesL.setColumns(20);
        AreaComponentesL.setRows(5);
        jScrollPane2.setViewportView(AreaComponentesL);

        jLabel2.setText("Fila:");

        jLabel1.setText("Col:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/folderopened-amarillo-icono-6397-32.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/disquetes-excepto-icono-3849-32.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/clicknrun-icono-4776-32.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(112, 447, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(numCol, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(numCol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String patron = ("(start|end|natural|integer|real|function|table|text|bit|infinity|pi|euler|if|else|during|from|to|do|terminal|expression|thread|main|convertion)|"
            + "([-|/|^|+|*])|"
            + "(=)|"
            + "([<|>|::|<=|>=]+)|"
            + "(AND|OR)|"
            + "([(|)])|"
            + "([.|,|;])|"
            + "([#])|"
            +"([0-9]+)|"
            + "([a-zA-Z_0-9]+)");
    String[] tipoDato= {"natural","integer","real","text","bit"};
    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        Dimension dim = this.getContentPane().getSize();
        panelPrincipal.setPreferredSize(dim);
    }//GEN-LAST:event_formComponentResized

    private void areaCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaCodigoKeyTyped
        // TODO add your handling code here:
//        cad+=evt.getKeyChar();
//        for (int i = 0; i < palRes.length; i++) {
//            if (cad.equals(palRes[i]+" ")) {
//                areaCodigo.setForeground(Color.red);
//                //System.out.println(cad);
//                cad="";
//            }
//        }
    }//GEN-LAST:event_areaCodigoKeyTyped

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");
        fc.setFileFilter(filtro);
        int r = fc.showOpenDialog(this);
        if(r == JFileChooser.APPROVE_OPTION){
            try{
                FileReader f = new FileReader(fc.getSelectedFile().getPath());
                BufferedReader bf = new BufferedReader(f);
                String cad = "";
                String temp = "";
                areaCodigo.setText("");
                while((cad=bf.readLine()) != null){
                    temp += cad+"\n";
                }
                temp = temp.substring(0, temp.length()-3);
                areaCodigo.setText(temp);
                bf.close();
            } catch(IOException e){
                e.printStackTrace();
                }
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");
        fc.setFileFilter(filtro);
        int r = fc.showSaveDialog(this);
        if(r == JFileChooser.APPROVE_OPTION){
            try{
                String ar[] = areaCodigo.getText().split("\n");
                FileWriter f = new FileWriter(fc.getSelectedFile().getPath()+".txt");
                BufferedWriter bf = new BufferedWriter(f);
                for(int i = 0; i < ar.length; i++){
                    bf.write(ar[i]);
                    bf.newLine();
                }
                bf.flush();
                bf.close();
                f.close();
            } catch(IOException e){
                e.printStackTrace();
                }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String texto = areaCodigo.getText();
        Simbolo simbolo = new Simbolo();
        String nombre = "";
        int linea=0;
        Pattern p = Pattern.compile(patron);
        Matcher matcher = p.matcher(texto);
        boolean bandera= false;
        String cad = "";

        while (matcher.find()){
            String tokenTipo1 = matcher.group(1);
            if(tokenTipo1 != null){
                cad+="Palabra Reservada: "+tokenTipo1+"\n";
                for(String tipo:tipoDato){
                    if (tokenTipo1.equals(tipo)) {
                        simbolo.tipo=tokenTipo1;
                    }
                }
            }

            String tokenTipo2 = matcher.group(2);
            if(tokenTipo2 != null){
                cad+="Operador Aritmetico: "+tokenTipo2+"\n";
            }

            String tokenTipo3 = matcher.group(3);
            if(tokenTipo3 != null){
                cad+="Operador de Asignación: "+tokenTipo3+"\n";
                if (!bandera) {
                    bandera=true;
                }
            }

            String tokenTipo4 = matcher.group(4);
            if(tokenTipo4 != null){
                cad+="Operador Relacional: "+tokenTipo4+"\n";
            }

            String tokenTipo5 = matcher.group(5);
            if(tokenTipo5 != null){
                cad+="Operador Lógico: "+tokenTipo5+"\n";
            }

            String tokenTipo6 = matcher.group(6);
            if(tokenTipo6 != null){
                cad+="Signo de Agrupación: "+tokenTipo6+"\n";
            }

            String tokenTipo7 = matcher.group(7);
            if(tokenTipo7 != null){
                cad+="Signo de Puntuación: "+tokenTipo7+"\n";
                if (tokenTipo7.equals(";")) {
                    if (!tablaSimbolos.contains(tokenTipo7)) {
                        tablaSimbolos.put(nombre, new Simbolo(simbolo.tipo, simbolo.valor, simbolo.fila));            
                        System.out.println("Nombre: "+nombre
                                   +"\nTipo: "+simbolo.tipo
                                   +"\nValor: "+simbolo.valor
                                   +"\nFila: "+linea);
                    }else{
                        javax.swing.JOptionPane.showMessageDialog(this,"El id ya existe");
                    }
                }
            }

            String tokenTipo8 = matcher.group(8);
            if(tokenTipo8 != null){
                cad+="Función Especial: "+tokenTipo8+"\n";
            }

            String tokenTipo9 = matcher.group(9);
            if(tokenTipo9 != null){
                cad+="Número: "+tokenTipo9+"\n";
                if (bandera) {
                    simbolo.valor=tokenTipo9;
                    bandera=false;
                }
            }

            String tokenTipo10 = matcher.group(10);
            if(tokenTipo10 != null){
                cad+="Identificador: "+tokenTipo10+"\n";
                if (!bandera) {
                    nombre= tokenTipo10;
                    linea= fila;
                }else{
                    simbolo.valor= tokenTipo10;
                    bandera=false;
                }
            }
        }
        AreaComponentesL.setText(cad);
    }//GEN-LAST:event_jButton4MouseClicked

    public void sobreIc(JLabel ic){
        ic.setBackground(Color.red);
        ic.setOpaque(true);
    }
    String cad = "";
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaComponentesL;
    private javax.swing.JTextArea areaCodigo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel numCol;
    private javax.swing.JLabel numFilas;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
